"""Color-vision-deficiency and grayscale simulation (Machado, Oliveira & Fernandes 2009, severity 1.0)."""
from __future__ import annotations

import itertools

from . import color
from .palette import Palette

MATRICES = {
    "protanopia": ((0.152286, 1.052583, -0.204868), (0.114503, 0.786281, 0.099216), (-0.003882, -0.048116, 1.051998)),
    "deuteranopia": ((0.367322, 0.860646, -0.227968), (0.280085, 0.672501, 0.047413), (-0.011820, 0.042940, 0.968881)),
    "tritanopia": ((1.255528, -0.076749, -0.178779), (-0.078411, 0.930809, 0.147602), (0.004733, 0.691367, 0.303900)),
}
KINDS = (*MATRICES, "grayscale")
ACCENTS = ("yellow", "blue", "cyan", "green", "purple", "subtle", "red", "orange")


def _lin(c: int) -> float:
    v = c / 255
    return v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4


def _gamma(v: float) -> int:
    v = min(1.0, max(0.0, v))
    s = 12.92 * v if v <= 0.0031308 else 1.055 * v ** (1 / 2.4) - 0.055
    return int(s * 255 + 0.5)


def simulate(hx: str, kind: str) -> str:
    r, g, b = (_lin(c) for c in color.parse_hex(hx))
    if kind == "grayscale":
        y = 0.2126 * r + 0.7152 * g + 0.0722 * b
        return color.to_hex((_gamma(y),) * 3)
    m = MATRICES[kind]
    return color.to_hex(tuple(_gamma(row[0] * r + row[1] * g + row[2] * b) for row in m))


def report(pal: Palette) -> str:
    header = "| {} | Normal | " + " | ".join(k.title() for k in KINDS) + " |"
    rule = "|---|---|" + "---|" * len(KINDS)
    lines = ["# Color vision and grayscale", "",
             "Generated by `tools/build.py` from `palette/umber-calm.toml`; do not edit. Simulation: Machado, "
             "Oliveira & Fernandes (2009), severity 1.0. Grayscale is relative luminance.", "",
             "Renderings of the sample code: [normal](renders/normal.svg) · [grayscale](renders/grayscale.svg) · "
             "[deuteranopia](renders/deuteranopia.svg) · [protanopia](renders/protanopia.svg) · "
             "[tritanopia](renders/tritanopia.svg).", "",
             "## Accents", "", header.format("Color"), rule]
    for name in ACCENTS:
        hx = pal.colors[name]
        lines.append(f"| `{name}` | `{hx}` | " + " | ".join(f"`{simulate(hx, k)}`" for k in KINDS) + " |")
    lines += ["", "## Separation of every accent pair", "",
              "ΔE_OK × 100 between the two colors as seen under each simulation; lower is harder to tell apart.", "",
              header.format("Pair"), rule]
    pairs = sorted((color.delta_e_ok(pal.colors[a], pal.colors[b]), a, b) for a, b in itertools.combinations(ACCENTS, 2))
    for normal, a, b in pairs:
        ha, hb = pal.colors[a], pal.colors[b]
        cells = [f"{color.delta_e_ok(simulate(ha, k), simulate(hb, k)):.1f}" for k in KINDS]
        lines.append(f"| {a} / {b} | {normal:.1f} | " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"
