local M = {}

--- Legacy syntax groups. Every one of them is a syntax mapping (spec §5.1) and is checked by the tests.
M.legacy_syntax = {
  "Comment",
  "Constant",
  "String",
  "Character",
  "Number",
  "Boolean",
  "Float",
  "Identifier",
  "Function",
  "Statement",
  "Conditional",
  "Repeat",
  "Label",
  "Operator",
  "Keyword",
  "Exception",
  "PreProc",
  "Include",
  "Define",
  "Macro",
  "PreCondit",
  "Type",
  "StorageClass",
  "Structure",
  "Typedef",
  "Special",
  "SpecialChar",
  "Tag",
  "Delimiter",
  "SpecialComment",
  "Debug",
  "Underlined",
  "Todo",
}

--- Captures that report a problem or a change inside source text: diagnostics contract (spec §5.1, §5.3).
M.diagnostic_captures = {
  ["Error"] = true,
  ["@comment.error"] = true,
  ["@comment.warning"] = true,
  ["@comment.note"] = true,
  ["@comment.todo"] = true,
  ["@diff.plus"] = true,
  ["@diff.minus"] = true,
  ["@diff.delta"] = true,
}

local function with(base, extra)
  return vim.tbl_extend("force", base, extra or {})
end

function M.build(c, opts)
  local s, u, d, t, x = c.syntax, c.ui, c.diag, c.term, c.tinted
  local st = opts.styles
  local bg = opts.transparent and "NONE" or u.bg
  local hl = {
    Normal = { fg = u.text, bg = bg },
    NormalNC = { fg = u.text, bg = opts.dim_inactive and u.chrome or bg },
    NormalFloat = { fg = u.text, bg = u.surface },
    FloatBorder = { fg = u.border_strong, bg = u.surface },
    FloatTitle = { fg = u.text, bg = u.surface, bold = true },
    Cursor = { fg = t.cursor_text, bg = t.cursor },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorLine = { bg = u.surface },
    CursorColumn = { bg = u.surface },
    ColorColumn = { bg = u.surface },
    CursorLineNr = { fg = u.line_number_active, bold = true },
    LineNr = { fg = u.line_number },
    SignColumn = { bg = bg },
    FoldColumn = { fg = u.text_dim, bg = bg },
    Folded = { fg = u.text_secondary, bg = u.surface },
    Visual = { fg = u.selection_fg, bg = u.selection_bg },
    VisualNOS = { link = "Visual" },
    Search = { fg = u.text, bg = x.search },
    IncSearch = { fg = u.bg, bg = d.search },
    CurSearch = { link = "IncSearch" },
    Substitute = { fg = u.bg, bg = d.search },
    MatchParen = { fg = u.text, bg = u.selection_bg, bold = true },
    Pmenu = { fg = u.text, bg = u.surface },
    PmenuSel = { fg = u.selection_fg, bg = u.selection_bg },
    PmenuSbar = { bg = u.surface },
    PmenuThumb = { bg = u.border },
    PmenuKind = { fg = s.type, bg = u.surface },
    PmenuExtra = { fg = u.text_secondary, bg = u.surface },
    StatusLine = { fg = u.text, bg = u.surface },
    StatusLineNC = { fg = u.text_secondary, bg = u.chrome },
    WinSeparator = { fg = u.border },
    VertSplit = { link = "WinSeparator" },
    WinBar = { fg = u.text, bg = bg },
    WinBarNC = { fg = u.text_secondary, bg = bg },
    TabLine = { fg = u.text_secondary, bg = u.chrome },
    TabLineFill = { bg = u.chrome },
    TabLineSel = { fg = u.text, bg = u.bg, bold = true },
    MsgArea = { fg = u.text },
    ModeMsg = { fg = u.text, bold = true },
    MoreMsg = { fg = s.string },
    ErrorMsg = { fg = d.error },
    WarningMsg = { fg = d.warning },
    Question = { fg = s["function"] },
    NonText = { fg = u.border },
    Whitespace = { fg = u.border_strong },
    EndOfBuffer = { fg = u.bg },
    SpecialKey = { fg = u.border },
    Title = { fg = s.heading, bold = true },
    Directory = { fg = s["function"] },
    Conceal = { fg = u.text_secondary },
    QuickFixLine = { bg = u.selection_bg },
    SpellBad = { sp = d.error, undercurl = true },
    SpellCap = { sp = d.warning, undercurl = true },
    SpellLocal = { sp = d.info, undercurl = true },
    SpellRare = { sp = d.hint, undercurl = true },
    DiffAdd = { bg = x.diff_add },
    DiffDelete = { bg = x.diff_delete },
    DiffChange = { bg = x.diff_change },
    DiffText = { bg = u.selection_bg, bold = true },
    Added = { fg = d.diff_add },
    Removed = { fg = d.diff_delete },
    Changed = { fg = d.diff_change },

    Comment = with({ fg = s.comment }, st.comments),
    Constant = { fg = s.constant },
    String = { fg = s.string },
    Character = { fg = s.string },
    Number = { fg = s.constant },
    Boolean = { fg = s.constant },
    Float = { fg = s.constant },
    Identifier = with({ fg = s.variable }, st.variables),
    Function = with({ fg = s["function"] }, st.functions),
    Statement = with({ fg = s.keyword }, st.keywords),
    Conditional = { link = "Statement" },
    Repeat = { link = "Statement" },
    Label = { link = "Statement" },
    Keyword = { link = "Statement" },
    Exception = { link = "Statement" },
    Operator = { fg = s.operator },
    PreProc = { fg = s.preproc },
    Include = { link = "PreProc" },
    Define = { link = "PreProc" },
    Macro = { link = "PreProc" },
    PreCondit = { link = "PreProc" },
    Type = { fg = s.type },
    StorageClass = { link = "Statement" },
    Structure = { link = "Type" },
    Typedef = { link = "Type" },
    Special = { fg = s.escape },
    SpecialChar = { fg = s.escape },
    Tag = { fg = s.tag },
    Delimiter = { fg = s.operator },
    SpecialComment = { fg = s.comment, bold = true },
    Debug = { fg = d.warning },
    Underlined = { underline = true },
    Error = { fg = d.error },
    Todo = { fg = u.bg, bg = d.warning, bold = true },

    ["@variable"] = { link = "Identifier" },
    ["@variable.builtin"] = { fg = s.builtin },
    ["@variable.parameter"] = with({ fg = s.variable }, st.parameters),
    ["@variable.member"] = { fg = s.variable },
    ["@property"] = { fg = s.variable },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = s.builtin },
    ["@constant.macro"] = { fg = s.preproc },
    ["@module"] = { fg = s.namespace },
    ["@label"] = { link = "Label" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = s.escape },
    ["@string.regexp"] = { fg = s.escape },
    ["@string.special"] = { fg = s.escape },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = s.type },
    ["@constructor"] = { fg = s.type },
    ["@attribute"] = { fg = s.preproc },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = s["function"] },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@function.macro"] = { fg = s.preproc },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.operator"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.bracket"] = { fg = s.operator },
    ["@punctuation.delimiter"] = { fg = s.operator },
    ["@punctuation.special"] = { fg = s.operator },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.error"] = { fg = d.error },
    ["@comment.warning"] = { fg = d.warning },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { fg = d.info },
    ["@tag"] = { fg = s.tag },
    ["@tag.attribute"] = { fg = s.attribute },
    ["@tag.delimiter"] = { fg = s.operator },
    ["@markup.heading"] = { fg = s.heading, bold = true },
    ["@markup.link"] = { fg = s.link, underline = true },
    ["@markup.link.url"] = { fg = s.link, underline = true },
    ["@markup.raw"] = { fg = s.code },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.list"] = { fg = s.operator },
    ["@markup.quote"] = { fg = u.text_secondary, italic = true },
    ["@diff.plus"] = { fg = d.diff_add },
    ["@diff.minus"] = { fg = d.diff_delete },
    ["@diff.delta"] = { fg = d.diff_change },

    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.mod.deprecated"] = { strikethrough = true },
    ["@lsp.typemod.variable.readonly"] = { link = "@variable" }, -- a `const` binding is a variable, not a constant

    DiagnosticError = { fg = d.error },
    DiagnosticWarn = { fg = d.warning },
    DiagnosticInfo = { fg = d.info },
    DiagnosticHint = { fg = d.hint },
    DiagnosticOk = { fg = d.ok },
    DiagnosticVirtualTextError = { fg = d.error, bg = x.error },
    DiagnosticVirtualTextWarn = { fg = d.warning, bg = x.warning },
    DiagnosticVirtualTextInfo = { fg = d.info, bg = x.info },
    DiagnosticVirtualTextHint = { fg = d.hint, bg = x.hint },
    DiagnosticUnderlineError = { sp = d.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = d.warning, undercurl = true },
    DiagnosticUnderlineInfo = { sp = d.info, undercurl = true },
    DiagnosticUnderlineHint = { sp = d.hint, undercurl = true },
    DiagnosticSignError = { fg = d.error },
    DiagnosticSignWarn = { fg = d.warning },
    DiagnosticSignInfo = { fg = d.info },
    DiagnosticSignHint = { fg = d.hint },
    DiagnosticFloatingError = { fg = d.error },
    DiagnosticFloatingWarn = { fg = d.warning },
    DiagnosticFloatingInfo = { fg = d.info },
    DiagnosticFloatingHint = { fg = d.hint },
    DiagnosticDeprecated = { strikethrough = true },
    DiagnosticUnnecessary = { fg = u.text_secondary },
    LspReferenceText = { bg = u.selection_bg },
    LspReferenceRead = { bg = u.selection_bg },
    LspReferenceWrite = { bg = u.selection_bg, underline = true },
    LspInlayHint = { fg = u.text_secondary, bg = u.surface },
    LspSignatureActiveParameter = { bold = true, underline = true },
  }

  require("umber-calm.groups.integrations").apply(hl, c, opts.integrations)
  return hl
end

return M
